### ISSUE TITLE
Tubular crash on Android Lollipop (5.1) phone; NewPipe on same phone doesn't

### ISSUE THREAD

**Issue by dftf-stu** [polymorphicshade/Tubular#324]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [x] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read and understood the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#ai-policy). The content of this bug report is not generated by AI.

### Affected version

0.28.2

### Steps to reproduce the bug

1. Tried to play this Digital Foundry video:
[DF Retro Super Show [#007]: How Unreal Engine 3 Dominated A Console Generation](https://www.youtube.com/watch?v=3h-zWHmeNgs)

### Expected behavior

Video should play without crashing the app, as it works fine in NewPipe 0.28.3 on the same device

### Actual behavior

Tubular crashes on that video (and some others), but NewPipe doesn't on the same videos

### Screenshots/Recordings

N / A

### Affected Android/Custom ROM version

Android 5.1 "Lollipop"

### Affected device model

Old Motorola phone

### Additional information

No issue with the same videos when played in NewPipe 0.28.3 on the same phone

So I guess in Tubular, issue might be to do with the Sponsor Block or Restore YouTube Dislike add-ons perhaps not working correctly? 🤔

Clearly I realise Android 5.1 won't be supported for much-longer by NewPipe (and therefore Tubular too, as a fork) though I'm not aware of the exact roadmap on this?

### Logs

**Crash report:**

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ <unknown_service>
* __Timestamp:__ 2026-02-10T19:10:40.205Z
* __Package:__ org.polymorphicshade.tubular
* __Service:__ <unknown_service>
* __Version:__ 0.28.2
* __OS:__ Linux Android 5.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
at org.schabi.newpipe.fragments.list.sponsorblock.SponsorBlockSegmentListAdapter$SponsorBlockSegmentItemViewHolder.updateFrom(SponsorBlockSegmentListAdapter.java:212)
at org.schabi.newpipe.fragments.list.sponsorblock.SponsorBlockSegmentListAdapter$SponsorBlockSegmentItemViewHolder.-$$Nest$mupdateFrom(SponsorBlockSegmentListAdapter.java:0)
at org.schabi.newpipe.fragments.list.sponsorblock.SponsorBlockSegmentListAdapter.onBindViewHolder(SponsorBlockSegmentListAdapter.java:87)
at org.schabi.newpipe.fragments.list.sponsorblock.SponsorBlockSegmentListAdapter.onBindViewHolder(SponsorBlockSegmentListAdapter.java:36)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7846)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7953)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6742)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:7013)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6853)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6849)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2422)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1722)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1682)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:747)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4133)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
at android.view.View.measure(View.java:17565)
at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1993)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:652)
at android.view.View.measure(View.java:17565)
at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:100)
at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2381)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.view.View.measure(View.java:17565)
at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(BottomSheetBehavior.java:515)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
at android.view.View.measure(View.java:17565)
at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
at android.view.View.measure(View.java:17565)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
at android.view.View.measure(View.java:17565)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1196)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by dftf-stu** [comment]
Okay, just tried Menu > ⚙Settings > 🛡SponsorBlock then set "Enable SponsorBlock" to off...

...and now, **no video** on the Digital Foundry channel crashes! 🥳

So... I _would_ try and white-list that channel, BUT seems the only way to do that is to load a video, then tap the 🛡 in the bottom-right, then tap "Whitelist channel".  Except... I **can't** do that, as the moment I try to access that tab on any Digital Foundry video, the app immediately crashes.  And it isn't possible in the SponsorBlock settings to add a channel into the whitelist there, so I'm a bit stuck!

**Comment by Baltazar500** [comment]
Same story on the final build. Tubular crashes when opening videos in subscriptions and playlists, but NewPipe of the same version works without problems

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-
* __App Language:__ ru
* __Service:__ <unknown_service>
* __Timestamp:__ 2026-03-21T12:30:22.073+10:00
* __Package:__ org.polymorphicshade.tubular
* __Service:__ <unknown_service>
* __Version:__ 0.28.4
* __OS:__ Linux Android 5.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
	at org.schabi.newpipe.fragments.list.sponsorblock.SponsorBlockSegmentListAdapter$SponsorBlockSegmentItemViewHolder.updateFrom(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:127)
	at org.schabi.newpipe.fragments.list.sponsorblock.SponsorBlockSegmentListAdapter.onBindViewHolder(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:13)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:170)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:1208)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:63)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:49)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:775)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:61)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:64)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17915)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:39)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
	at androidx.core.widget.NestedScrollView.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:1)
	at android.view.View.measure(View.java:17915)
	at androidx.viewpager.widget.ViewPager.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:234)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:7)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:93)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:382)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
	at android.view.View.measure(View.java:17915)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:54)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:382)
	at android.view.View.measure(View.java:17915)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:248)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(r8-map-id-4103cd55080d6c1e91507715747b364942351cd27678e8b6f80e0ea57b476341:160)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2731)
	at android.view.View.measure(View.java:17915)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2413)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1415)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1639)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1293)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6599)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

```
</details>
<hr>

And as in the message above, after disabling SponsorBlock the crashes stopped. But Tubular without SponsorBlock is NewPipe :|

**Comment by dftf-stu** [comment]
@krystian3w : if you have a comment or thought to add, perhaps do-so, rather than just mark each of my comments as 😕

Are you implying you are having the same issue?

**Comment by dftf-stu** [comment]
Looks like in [NewPipe 13438](https://github.com/TeamNewPipe/NewPipe/issues/13438) , the team there are now actively discussing dropping support for Android 5.x devices, though unclear from which version (e.g. 0.29 or 0.30) this would be from... 🤔

**Comment by Baltazar500** [comment]
@dftf-stu, Yes, I read this thread :/ NewPipe/Tubular/etc on Android 5.1 will not work for long :(

**Comment by dftf-stu** [comment]
Closing ticket

The NewPipe team have just released version 0.28.6, which adds a pop-up message to users on Android 5.x to advise the next version, 0.28.7, will no-longer run on that OS.  By the time the developer of Tubular next pulls code from their project into this one, support will have been removed from the code, so there's little point now keeping this open.
